import { boolean, number, object, string, type ZodSchema } from "zod";
import {
  CurrencyEnum,
  ScaleEnum,
  StatusEnum,
  dateSchema,
} from "../shared.schema";
import { customerResponseSchema } from "./Customers.schema";

const lineSchema = object({
  id: string(),
  checkout_line_id: string(),
  product_id: string(),
  product_version_id: string(),
  product_name: string(),
  product_image_url: string().nullable(),
  subscription_interval_value: number().nullable(),
  subscription_interval_scale: ScaleEnum.nullable(),
  gift: boolean(),
  gift_to_customer: customerResponseSchema.nullable(),
  selected_gameserver_id: string().nullable(),
  price: number(),
  price_str: string(),
  quantity: number(),
  discount_amount: number(),
  discount_amount_str: string(),
  subtotal_amount: number(),
  subtotal_amount_str: string(),
  tax_amount: number(),
  tax_amount_str: string(),
  total_amount: number(),
  total_amount_str: string(),
});

export const orderResponseSchema: ZodSchema = object({
  id: string(),
  pretty_id: string(),
  store_id: string(),
  customer: customerResponseSchema,
  status: StatusEnum,
  checkout_id: string(),
  subscription_id: string().nullable(),
  is_subscription: boolean(),
  coupon_id: string().nullable(),
  giftcard_id: string().nullable(),
  billing_name: string(),
  billing_email: string(),
  billing_country: string(),
  customer_ip: string(),
  currency: CurrencyEnum,
  tax_inclusive: boolean(),
  discount_amount: number(),
  discount_amount_str: string(),
  subtotal_amount: number(),
  subtotal_amount_str: string(),
  tax_amount: number(),
  tax_amount_str: string(),
  giftcard_usage_amount: number(),
  giftcard_usage_amount_str: string(),
  total_amount: number(),
  total_amount_str: string(),
  billing_cycle_sequence: number().nullable(),
  lines: lineSchema.array().nullable(),
  created_at: dateSchema,
  completed_at: dateSchema.nullable(),
  canceled_at: dateSchema.nullable(),
});

export const orderLookupSchema: ZodSchema = object({
  order_id: string(),
  subscription_id: string(),
  is_subscription: boolean(),
  limit: number(),
  after: string(),
  before: string(),
}).partial();
